# -*- coding: utf-8 -*-
"""Generate SEED_class_codes.sql from the Class Code Mapping Template.

⚠️ NEITHER THIS SCRIPT'S OUTPUT NOR THE WORKBOOK IS COMMITTED. GitHub Pages
   serves the whole repo publicly, so a data-bearing .sql in it is published at
   pmodepartment.github.io/prc-app/… bypassing auth and RLS. Same rule as
   SEED_vendor_masterlist.sql. .gitignore carries a glob guard for both.

Usage:  python gen_class_codes.py "path/to/EPC. FIN. Class Code Mapping Template.xlsx"
Then run the generated SEED_class_codes.sql in the Supabase SQL Editor.
"""
import sys, re, io
from collections import OrderedDict

try:
    import openpyxl
except ImportError:
    sys.exit('pip install openpyxl')

SRC = sys.argv[1] if len(sys.argv) > 1 else None
if not SRC:
    sys.exit(__doc__)

ws = openpyxl.load_workbook(SRC, data_only=True)['Excel Temp']

# ⚠️ Column A is EMPTY in this template — the data starts at column B. Reading
#    from A is what made the first extraction return zero rows.
rows = []
for r in ws.iter_rows(min_row=10, values_only=True):
    v = [('' if c is None else str(c).strip()) for c in (list(r) + [''] * 9)[:9]]
    l1, l2, l3, d1, d2, d3 = v[1], v[2], v[3], v[5], v[6], v[7]
    if not re.fullmatch(r'\d{2}', l1) or not l3:
        continue
    rows.append((l1, l2, l3, d1, d2, d3))

L1, L2, L3 = OrderedDict(), OrderedDict(), OrderedDict()
for i, (a, b, c, d1, d2, d3) in enumerate(rows):
    L1.setdefault(a, (d1, i))
    if b:
        L2.setdefault(b, (a, d2, i))
    L3.setdefault(c, (a, b, d3, i))

def q(s):
    return "'" + str(s).replace("'", "''") + "'"

out = []
out.append('-- Class code master data — generated by gen_class_codes.py. DO NOT COMMIT.')
out.append('-- Run AFTER migrations/2026-09-05_class_codes.sql.')
out.append('-- Idempotent: re-running updates names and re-activates, and never deletes')
out.append('-- a code that rates are already filed under.')
out.append('')
# Deactivate first, then upsert: a code dropped from a re-issued template stops
# being offered but keeps its history. NEVER delete — vendor_rates points here.
out.append('update public.class_codes set active = false;')
out.append('')

def emit(label, tuples):
    """tuples: (code, level, parent, name, l1, l2, sort)"""
    if not tuples:
        return
    out.append('-- ' + label + ' (%d)' % len(tuples))
    CH = 200
    for i in range(0, len(tuples), CH):
        chunk = tuples[i:i + CH]
        out.append('insert into public.class_codes '
                   '(code, level, parent_code, name, l1_code, l2_code, sort_order, active) values')
        vals = []
        for code, lvl, par, name, l1, l2, srt in chunk:
            vals.append('  (%s, %d, %s, %s, %s, %s, %d, true)' % (
                q(code), lvl, q(par) if par else 'null', q(name), q(l1),
                q(l2) if l2 else 'null', srt))
        out.append(',\n'.join(vals))
        out.append('on conflict (code) do update set')
        out.append('  level = excluded.level, parent_code = excluded.parent_code,')
        out.append('  name = excluded.name, l1_code = excluded.l1_code,')
        out.append('  l2_code = excluded.l2_code, sort_order = excluded.sort_order,')
        out.append('  active = true;')
        out.append('')

# ⚠️ LEVEL ORDER MATTERS — parent_code is a real FK, so a child inserted before
#    its parent fails. 1 then 2 then 3.
emit('Level 1 — categories',
     [(c, 1, None, n, c, None, i) for c, (n, i) in L1.items()])
emit('Level 2 — groups',
     [(c, 2, p, n, p, None, i) for c, (p, n, i) in L2.items()])
emit('Level 3 — items',
     [(c, 3, (p2 or p1), n, p1, (p2 or None), i) for c, (p1, p2, n, i) in L3.items()])

out.append('-- report')
out.append("select level, count(*) as codes, count(*) filter (where active) as active")
out.append('  from public.class_codes group by level order by level;')
out.append('')

io.open('SEED_class_codes.sql', 'w', encoding='utf-8', newline='').write('\n'.join(out))
print('wrote SEED_class_codes.sql — %d L1, %d L2, %d L3 (%d rows total)'
      % (len(L1), len(L2), len(L3), len(L1) + len(L2) + len(L3)))
